### CSCI561 - Fall 2014 - Sample Makefile

### Example for a C++ agent:
###agent: agent.cpp
###	g++ agent.cpp -o agent
###
###run: agent
###	./agent
###
### For Java you might use:

agent: FOLInferenceBC.class
	
agent.class: FOLInferenceBC.java
	javac FOLInferenceBC.java

run: FOLInferenceBC.class
	java FOLInferenceBC


### For python or other non-compiled languages:
#agent:
#	
#run:
#	./agent.py

